### ISSUE TITLE
Neither controller nor views created

### ISSUE THREAD

**Issue by gdiazderadaa** [cakebake/yii2-actionlog#2]
Hi there,
Do I need to manually run Gii to create controller and related views? As per the Readme.md doesn´t seem so, but I ran the migration and no file have been created, or at least, I couldn´t find it.
Thanks in advance

**Comment by gdiazderadaa** [comment]
Just realized that they were in the vendor folder. Do I need to be logged in order the plugin to work?

**Comment by cakebake** [comment]
No. Please see https://github.com/cakebake/yii2-actionlog#configuration

**Comment by gdiazderadaa** [comment]
Had already applied the configuration following the doc, but the table actionlog remains empty after being done a lot of actions. No action is logged.

**Comment by cakebake** [comment]
I haven´t currently an active yii2 prodject to test this. Sorry. :/ Please check your error logs / stacktraces to check for possible errors.

**Comment by gdiazderadaa** [comment]
After digging deeper into your source files, saw the Behavior and its comment so guessed I should add it to every model I want to be using the ActionLog. Would be helpful if you can add it to the configuration steps within the documentation. Is there any way to config the actionlog message in the behavior, to log, for example, the id of the element being created/read/updated/deleted? This is what I'm getting right now: 	`s:57:"cakebake\actionlog\behaviors\ActionLogBehavior::afterFind";`
Thanks in advance

**Comment by gdiazderadaa** [comment]
@cakebake can you please tell me whether there´s an easy way to accomplish what states my post above? Many thanks in advance?
