### ISSUE TITLE
doesn't create logs automatically

### ISSUE THREAD

**Issue by fdo36** [cakebake/yii2-actionlog#4]
In the README you said this module 

> Automatically logs user actions like create, update, delete

But it doesn't. This module does not logs automatically the actions, I need to add manually the `ActionLog::add()` function.

Another thing: you need to change your composer.json to this:

```
"minimum-stability": "dev",
"prefer-stable": true,
```
to make the installation succesful.

**Comment by Denbora** [comment]
There is comment in the code. I think it could help =)

/**
 * To use ActionLogBehavior, simply insert the following code to your ActiveRecord class:
 *
 * ```php
 * public function behaviors()
 * {
 *     return [
 *          'actionlog' => [
 *              'class' => 'cakebake\actionlog\behaviors\ActionLogBehavior',
 *          ],
 *     ];
 * }
 * ```
 */

But it's good point about minimum-stability options. It's head-ache to install this package without this lines in composer.json =)
"minimum-stability": "dev",
"prefer-stable": true,
