### ISSUE TITLE
OCIStmtExecute: ORA-00904: 'NOW' invalid identifier

### ISSUE THREAD

**Issue by fdo36** [cakebake/yii2-actionlog#6]
I use a oracle database (11g) and the application throws me that error when I try to use the function:

`ActionLog::add()`

It seems the problem is that oracle doesn't support the identifier 'NOW'. You use it as default behaviour in your ActionLog.php:

`public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'time',
                ],
	            'value' => new Expression('NOW()'),
            ],
        ];
    }`

is there anything I can use to set my own value for the time in my code without modifying the widget's code?

**Comment by cakebake** [comment]
Hey @fdo36,

this module is no longer supported by me and has no future plans. You could create a fork and use the optimzed code for your project.

Thanks for your feedback!
